[package]
name = "function"
version = "0.1.0"
authors = ["baremaximum <therealcharlesdesbiens@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
log = "0.4.14"
actix-http = "2.2.0"